# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cptest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Torus-fetchNodeDetails', :path=>"../"
  # Pods for cptest
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
  end
end
